# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage:
  jobs: 
  - job: Build

    steps:
    - script: echo Build Stage
    displayName: 'Run a one-line script'

- stage:
  jobs: 
  - job: Deploy to Dev

    steps:
    - script: echo Deploy to Dev
    displayName: 'Run a one-line script'

- stage:
  jobs: 
  - job: Deploy to QA

    steps:
    - script: echo Deploy to QA
    displayName: 'Run a one-line script'
